apiVersion: batch/v1
kind: CronJob
metadata:
  name: gitops-cron
  namespace: gitops
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          namespace: gitops
        spec:
          restartPolicy: Never
          serviceAccountName: gitops-serviceaccount
          containers:
          - name: gitops-operator
            image: jehadnasser/demo-go-app:latest
            command: [sh, -e, -c]
            args:
            - git clone https://github.com/jehadnasser/demo-deploy.git /tmp/example &&
              kubectl apply -f /tmp/example/namespace.yaml &&
              find /tmp/example -name '*.yaml' ! -name 'namespace.yaml' -exec kubectl apply -f {} \;